---
title: "CV"
---

## Education

- **Ph.D in Statistics**, Arizona State University, 2019-2023
- **B.A. in Mathematics and Economics**, Georgetown University, 2008-2012

## Work Experience

### University of Texas at Austin
Postdoctoral Fellow (Summer 2023-Present)

### Microsoft
Data Scientist Intern (Summer 2021)

### Arize AI
Data Science Intern (Summer 2020)

### Oliver Wyman
- Senior Analyst, Retail and Business Banking Consumer Insights Group (Winter 2018 - Summer 2019)
- Analyst, Retail and Business Banking Consumer Insights Group (Summer 2014 - Winter 2018)

### Cornerstone Research
Analyst (Summer 2012 - Summer 2014)

## Skills

Programming:
- C / C++
- Python
- R

Product Management:
- Build, maintain, and develop "product discipline" (including [RFC process](https://github.com/StochasticTree/rfcs)) for [stochtree](https://stochtree.ai/) (open-source decision tree software suite)

## Teaching

- **MAT 270** (Calculus with Analytic Geometry I) Recitation, Fall 2020
- **MAT 271** (Calculus with Analytic Geometry II) Recitation, Fall 2021
- **MAT 271** (Calculus with Analytic Geometry II) Recitation, Spring 2022
